### PR TITLE
lth fix

### PR DESCRIPTION
**Pull request by inshaal**
Well guess what. I lost 3marks in my test just because of this lth thing. Rudra sir and other teachers have said that it is always raised to the power 3 irrespective of no. of the digits. 

Also, That website was displaying wrong information. Fix this thing asap before others make this mistake!

### CODE REVIEW

**Comment by disc0nnctd** [comment]
I am doing what is right.
Also, I don't intend to direct it towards students of any specific school who have stubborn teachers (or/and less knowledgeable).

Pull request denied.

**Comment by inshaal** [comment]
Anyway, will confirm with other teachers 👍

**Comment by disc0nnctd** [comment]
Didn't change the code but added a footnote as NCERT also says "1^3 = 3".
Thanks for raising the issue.

The mindset with which the programs are shared in this repo isn't limited to marks in tests, anyway.

**Comment by inshaal** [comment]
Okay..

**Pull request closed without merging**
